spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        SQL: debug
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: debug

  jackson:
    default-property-inclusion: non_null

  redis:
    host: 121.134.10.94
    port: 20102

  datasource:
    master:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://synology.freshr.run:10405/postgres
        username: postgres
        password: dltkdgoTl#001
        minimumIdle: 200
        maximumPoolSize: 200
        poolName: SpringBootJPAHikariCP
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          useLocalTransactionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
    slave:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://synology.freshr.run:10405/postgres
        username: postgres
        password: dltkdgoTl#001
        minimumIdle: 200
        maximumPoolSize: 200
        poolName: SpringBootJPAHikariCP
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          useLocalTransactionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false

  mail:
    host: XXX.XXX.XXX
    port: 587
    username: XXX@XXX.XXX
    password: XXX

logging:
  level:
    org:
      hibernate:
        type: debug
  file:
    path: ./.log
  logback:
    rollingpolicy:
      max-file-size: 30MB
      max-history: 10

freshr:
  elasticsearch:
    url: synology.freshr.run:10408

  email:
    from: XXX@XXX.XXX