server:
  port: 80

spring:
  profiles:
    active: test

  session:
    store-type: none

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  mvc:
    static-path-pattern: /resources/**

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: false
        SQL: error
        format_sql: false
        use_sql_comments: false
        type:
          descriptor:
            sql: error
        jdbc:
          batch_size: 5
        default_batch_fetch_size: 1000

  datasource:
    hikari:
      minimumIdle: 200
      maximumPoolSize: 200
      poolName: SpringBootJPAHikariCP
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 580000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

logging:
  level:
    org:
      hibernate:
        type: error

freshr:
  minio:
    bucket: blog
    access: blog
    secret: dltkdgoTl#001
    domain: https://minio-api.freshr.run
    path: upload
    except:
      - test

  rsa:
    limit: 300
