spring:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  redis:
    host: localhost
    port: 63791

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver

  mail:
    host: XXX.XXX.XXX
    port: 587
    username: XXX@XXX.XXX
    password: XXX

### AWS S3 Settings Start
#cloud:
#  aws:
#    stack:
#      auto: false
#    region:
#      static: ap-northeast-2
#    credentials:
#      profile-name: test
#
#freshr:
#  s3:
#    path: upload
#    except:
#      - test
#      - dev
#      - staging
#      - prod
#    bucket: BUCKET_NAME
### AWS S3 Settings Finish

### Physical Attach Settings Start
#spring:
#  servlet:
#    multipart:
#      location: /upload/.temp
#
#freshr:
#  attach:
#    root: upload
#    domain: http://localhost:8900
#    pathList:
#      - community
#      - editor
#      - user
#    extensionList:
#      - jpg
#      - png
#      - gif
#    except:
#      - test
#      - dev
#      - staging
#      - prod
### Physical Attach Settings Finish

logging:
  level:
    org:
      hibernate:
        type: trace

freshr:
  exceptions:
    success-message: 처리되었습니다.

  email:
    from: XXX@XXX.XXX